window.IMMBA = {
  faculty: [
    { type: "full", zhName: "杜逸寧", enName: "Yi-Ning Tu", deptZh: "統計資訊系專任", deptEn: "Department of Statistics and Information Science", titleZh: "副教授兼國際經營管理碩士(imMBA)主任", titleEn: "Associate Professor and Director of imMBA", eduZh: "政治大學資訊管理學博士", eduEn: "Ph.D. in Information Management, National Chengchi University", fieldsZh: "資料探勘、文字探勘、人工智慧、機器學習、資訊檢索", fieldsEn: "Data mining, text mining, AI, machine learning, information retrieval", phone: "#3988, LM208-2", email: "082435@mail.fju.edu.tw", site: "https://sites.google.com/view/yiningtu" },
    { type: "full", zhName: "李天行", enName: "Tien-Hsing Lee", deptZh: "商學博士班專任", deptEn: "Ph.D. Program in Business Administration", titleZh: "講座教授（前國際與資源發展副校長）", titleEn: "Chair Professor; former Vice President for International and Resource Development", eduZh: "美國奧斯汀德州大學作業研究與工業工程博士", eduEn: "Ph.D. in Operations Research and Industrial Engineering, The University of Texas at Austin", fieldsZh: "顧客關係管理、人工智慧、應用統計、作業研究", fieldsEn: "CRM, artificial intelligence, applied statistics, operations research", phone: "#2905, SL228", email: "036665@mail.fju.edu.tw" },
    { type: "full", zhName: "林耀南", enName: "Yao-Nan Lin", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "教授（前國際教育長）", titleEn: "Professor; former Dean of International Education", eduZh: "美國舊金山金門大學企業管理博士", eduEn: "DBA, Golden Gate University", fieldsZh: "消費者心理學、產品與行銷創新、創造力、人力資源管理", fieldsEn: "Consumer psychology, product and marketing innovation, creativity, HRM", phone: "#2735, SL260", email: "065999@mail.fju.edu.tw" },
    { type: "full", zhName: "許育銘", enName: "Yu-Ming Hsu", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "副教授兼科技管理碩士學程主任", titleEn: "Associate Professor and Director, Master's Program in Technology Management", eduZh: "台灣大學國際企業研究所博士", eduEn: "Ph.D. in International Business, National Taiwan University", fieldsZh: "行銷管理、數位行銷、資訊科技行銷、社群商務、國際企業管理", fieldsEn: "Marketing management, digital marketing, IT marketing, social commerce, international business", phone: "#3977, SL225", email: "155456@mail.fju.edu.tw" },
    { type: "full", zhName: "林芷安", enName: "Chih-An Lin", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "副教授兼學術交流中心主任", titleEn: "Associate Professor and Director, Academic Exchange Center", eduZh: "台灣大學國際企業博士", eduEn: "Ph.D. in International Business, National Taiwan University", fieldsZh: "供應鏈管理、媒體傳播、整合行銷、品牌管理", fieldsEn: "Supply chain management, media communication, IMC, brand management", phone: "#2924, SL221", email: "144629@mail.fju.edu.tw" },
    { type: "full", zhName: "黃愷平", enName: "Kai-Ping Huang", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "副教授", titleEn: "Associate Professor", eduZh: "澳洲雪梨科技大學企業管理博士", eduEn: "Ph.D. in Business Administration, University of Technology Sydney", fieldsZh: "中小企業、創業精神、行銷管理、人力資源管理", fieldsEn: "SMEs, entrepreneurship, marketing, HRM", phone: "#2906", email: "129741@mail.fju.edu.tw" },
    { type: "full", zhName: "曾祥景", enName: "Hsiang-Ching Tseng", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "副教授", titleEn: "Associate Professor", eduZh: "政治大學企業管理博士", eduEn: "Ph.D. in Business Administration, National Chengchi University", fieldsZh: "行銷相關領域", fieldsEn: "Marketing", phone: "#2737", email: "142652@mail.fju.edu.tw" },
    { type: "full", zhName: "林玫君", enName: "Mei-Chun Lin", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "副教授", titleEn: "Associate Professor", eduZh: "成功大學工業與資訊管理博士", eduEn: "Ph.D. in Industrial and Information Management, National Cheng Kung University", fieldsZh: "產業分析與競爭策略、科技創新、服務行銷、供應鏈管理", fieldsEn: "Industry analysis, technology innovation, services marketing, supply chain", phone: "#2968, SL408", email: "151308@mail.fju.edu.tw" },
    { type: "full", zhName: "鄭淑玲", enName: "Shu-Ling Cheng", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "副教授", titleEn: "Associate Professor", eduZh: "成功大學企業管理系博士", eduEn: "Ph.D. in Business Administration, National Cheng Kung University", fieldsZh: "行銷研究、資料分析、國際金融", fieldsEn: "Marketing research, data analytics, international finance", phone: "#2725, SL211", email: "151667@mail.fju.edu.tw" },
    { type: "full", zhName: "胡碧嬋", enName: "Pi-Chan Hu", deptZh: "跨文化研究所專任", deptEn: "Graduate Institute of Cross-Cultural Studies", titleZh: "副教授（前學術交流中心主任）", titleEn: "Associate Professor; former Director, Academic Exchange Center", eduZh: "政治大學應用英語語言學博士", eduEn: "Ph.D. in Applied English Linguistics, National Chengchi University", fieldsZh: "國際商務談判、法律語言學、財經法律翻譯、法律與醫療口筆譯", fieldsEn: "International business negotiation, legal linguistics, translation and interpreting", phone: "#2145", email: "128144@mail.fju.edu.tw" },
    { type: "full", zhName: "林淑雯", enName: "Shu-Wen Lin", deptZh: "", deptEn: "", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "英國杜倫大學教育博士", eduEn: "Ed.D., Durham University", fieldsZh: "通識及專業英文、世界性英語", fieldsEn: "ESP/EAP and world Englishes", phone: "#3362, SF829", email: "156503@mail.fju.edu.tw" },
    { type: "full", zhName: "江翠玲", enName: "Tsui-Ling Chiang", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "輔仁大學商學研究所博士", eduEn: "Ph.D. in Business Administration, Fu Jen Catholic University", fieldsZh: "經濟學、財務管理與公司治理、投資學、國際財務管理、信用風險", fieldsEn: "Economics, corporate finance and governance, investments, international finance, credit risk", phone: "#2852, SL472", email: "051266@mail.fju.edu.tw" },
    { type: "full", zhName: "顏孟賢", enName: "Meng-Hsien Yen", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "政治大學企業管理學系博士", eduEn: "Ph.D. in Business Administration, National Chengchi University", fieldsZh: "一般管理、策略管理、國際企業", fieldsEn: "General management, strategy, international business", phone: "#2648", email: "145785@mail.fju.edu.tw" },
    { type: "full", zhName: "徐皓馨", enName: "Hao-Hsin Hsu", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "交通大學管理科學系博士", eduEn: "Ph.D. in Management Science, National Yang Ming Chiao Tung University", fieldsZh: "組織行為、職場健康心理學、人力資源管理、效率及生產力分析", fieldsEn: "Organizational behavior, occupational health psychology, HRM, productivity analysis", phone: "#2771", email: "144779@mail.fju.edu.tw" },
    { type: "full", zhName: "黃凱斌", enName: "Kai-Pin Huang", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "交通大學工業工程與管理學系博士", eduEn: "Ph.D. in Industrial Engineering and Management, National Yang Ming Chiao Tung University", fieldsZh: "統計推論、品質工程、資料探勘與機器學習、人工智慧應用", fieldsEn: "Statistical inference, quality engineering, data mining and machine learning, AI applications", phone: "#6265", email: "152400@mail.fju.edu.tw" },
    { type: "full", zhName: "黃慶偉", enName: "Ching-Wei Huang", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "中正大學財務金融博士", eduEn: "Ph.D. in Finance, National Chung Cheng University", fieldsZh: "投資學、行為財務、綠色金融、氣候與永續金融", fieldsEn: "Investments, behavioral finance, green, climate and sustainable finance", phone: "#2678", email: "158325@mail.fju.edu.tw" },
    { type: "full", zhName: "王滄賢", enName: "Tsang-Hsien Wang", deptZh: "金融與國際企業學系專任", deptEn: "Department of Finance and International Business", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "臺灣科技大學管理研究所博士", eduEn: "Ph.D. in Management, National Taiwan University of Science and Technology", fieldsZh: "消費者行為、行銷管理、創新與產品管理、國際企業、品牌管理", fieldsEn: "Consumer behavior, marketing, innovation and product management, international business, branding", phone: "#3931", email: "167167@mail.fju.edu.tw" },
    { type: "full", zhName: "林佳樺", enName: "Chia-Hua Lin", deptZh: "企業管理系專任", deptEn: "Department of Business Administration", titleZh: "助理教授", titleEn: "Assistant Professor", eduZh: "中正大學心理學系博士", eduEn: "Ph.D. in Psychology, National Chung Cheng University", fieldsZh: "組織行為、工商心理學", fieldsEn: "Organizational behavior and industrial-organizational psychology", phone: "#2966", email: "167208@mail.fju.edu.tw" },
    { type: "adjunct", zhName: "王慧美", enName: "Hui-Mei Wang", deptZh: "", deptEn: "", titleZh: "兼任副教授（前國際經營管理碩士(imMBA)主任）", titleEn: "Adjunct Associate Professor; former Director of imMBA", eduZh: "台灣大學國際企業博士", eduEn: "Ph.D. in International Business, National Taiwan University", fieldsZh: "國際企業、國際行銷", fieldsEn: "International business and international marketing", phone: "", email: "wanghm.tw@gmail.com" }
  ],
  news: [
    { id: "admission-116", date: "2026-08-19", pinned: true, zhTitle: "（國際經管－全英 MBA）116 學年度甄試招生報名：2026/09/30–10/13", enTitle: "Domestic screening admission for 2027 entry: apply 30 Sep–13 Oct 2026", zhBody: "本地生甄試管道免筆試，採書審與口試。口試以英文為主、中文為輔。請於報名期間完成線上申請並備妥規定文件。外國學生請改走國際生申請管道。", enBody: "The screening track for local applicants has no written exam. Admission is based on document review and an interview conducted mainly in English. International applicants should follow the English-language admission track." },
    { id: "career-platform", date: "2025-01-30", pinned: true, zhTitle: "管理學院職涯平台：工作職缺", enTitle: "College of Management career platform: job openings", zhBody: "管理學院職涯平台持續更新實習與全職職缺，歡迎在學與畢業同學多加利用。", enBody: "The College of Management career platform lists internships and full-time openings for current students and alumni." },
    { id: "intl-mba", date: "2026-09-15", pinned: false, zhTitle: "你身邊有正在考慮 MBA 的國際學生嗎？", enTitle: "Know an international student considering an MBA?", zhBody: "國際經管採全英語授課，本地生與國際學生約 1:1 合班。歡迎將招生資訊轉介給正在尋找亞洲全英 MBA 的朋友。", enBody: "imMBA is taught entirely in English, with local and international students studying together in roughly equal numbers. Please share this opportunity with friends exploring an English-taught MBA in Asia." },
    { id: "two-years", date: "2026-09-08", pinned: false, zhTitle: "碩士兩年，可以有多大可能？", enTitle: "How much is possible in two years?", zhBody: "兩年期間，同學可完成 MBA 學位、申請跨國雙碩士，或透過姊妹校交換累積跨文化經驗。", enBody: "In two years, students can complete the MBA, pursue a dual master’s degree, or join a tuition-waiver exchange at a partner university." },
    { id: "ai-product", date: "2026-09-02", pinned: false, zhTitle: "90 Seconds with the Professor｜AI × Product", enTitle: "90 Seconds with the Professor | AI × Product", zhBody: "教師短講系列介紹人工智慧如何進入產品決策與創新流程。", enBody: "A short faculty series on how artificial intelligence enters product decisions and innovation." },
    { id: "data-analytics", date: "2026-08-26", pinned: false, zhTitle: "New Course Spotlight｜Data Analytics for International Business", enTitle: "New Course Spotlight | Data Analytics for International Business", zhBody: "新開課程聚焦國際企業情境下的資料分析能力。", enBody: "A new course focusing on analytics skills for international business settings." },
    { id: "ai-product-dev", date: "2026-08-19", pinned: false, zhTitle: "New Course Spotlight｜AI-Assisted Digital Product Development", enTitle: "New Course Spotlight | AI-Assisted Digital Product Development", zhBody: "新課程結合數位產品開發與生成式 AI 工具應用。", enBody: "A new course combining digital product development with generative AI tools." },
    { id: "summer-pause", date: "2026-08-05", pinned: false, zhTitle: "Summer Pause", enTitle: "Summer Pause", zhBody: "夏季期間辦公室服務時間請以公告為準，緊急事項請先來信。", enBody: "Office hours during the summer break follow the latest announcement. For urgent matters, please email the office." },
    { id: "iqs-spotlight", date: "2026-07-29", pinned: false, zhTitle: "Partner Spotlight｜IQS School of Management", enTitle: "Partner Spotlight | IQS School of Management", zhBody: "巴塞隆納 IQS 為跨國雙碩士夥伴，學生可於碩二修讀數位環境國際行銷或工業經營管理碩士。", enBody: "IQS in Barcelona is a dual-degree partner. Year-two students may pursue International Marketing in a Digital Environment or Industrial Business Management." },
    { id: "leaders", date: "2026-07-22", pinned: false, zhTitle: "當世界快速變動，我們該培養什麼樣的領導者？", enTitle: "What kind of leaders should we cultivate in a rapidly changing world?", zhBody: "課程與活動設計強調跨文化協作、數位創新與負責任的管理決策。", enBody: "The curriculum emphasizes cross-cultural collaboration, digital innovation, and responsible management." },
    { id: "pacific", date: "2026-07-15", pinned: false, zhTitle: "跨越太平洋，國際夥伴再＋1", enTitle: "Across the Pacific, one more global partner", zhBody: "管理學院持續拓展北美學術合作，為國際經管學生增加交流選項。", enBody: "The College continues to expand North American partnerships and mobility options for imMBA students." },
    { id: "kedge-paris", date: "2026-04-29", pinned: false, zhTitle: "KEDGE 校區三｜Paris 巴黎", enTitle: "KEDGE campus III | Paris", zhBody: "KEDGE 雙聯學生可認識巴黎校區的學習與城市資源。", enBody: "An introduction to KEDGE’s Paris campus for dual-degree students." }
  ],
  gallery: [
    { src: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80", zh: "全英語課堂討論", en: "English-taught seminar" },
    { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80", zh: "跨國學生合作", en: "International teamwork" },
    { src: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80", zh: "個案與產業對話", en: "Case discussion" },
    { src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80", zh: "資料與決策分析", en: "Analytics and decisions" },
    { src: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80", zh: "國際交流活動", en: "Global engagement" },
    { src: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", zh: "校園與學院空間", en: "Campus and college spaces" },
    { src: "https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=1200&q=80", zh: "畢業典禮", en: "Commencement" },
    { src: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80", zh: "海外交換與雙碩士", en: "Exchange and dual degrees" }
  ],
  events: [
    { date: "2026-07-29", zhTitle: "Partner Spotlight｜IQS School of Management", enTitle: "Partner Spotlight | IQS School of Management", zh: "跨國雙碩士夥伴介紹與課程選擇說明。", en: "Introduction to the IQS dual-degree tracks." },
    { date: "2026-05-21", zhTitle: "國際專業參訪｜義大利", enTitle: "International study visit | Italy", zh: "管理學院 2026 國際專業參訪紀實。", en: "College of Management 2026 professional visit." },
    { date: "2026-06-03", zhTitle: "管院戶外英語角", enTitle: "Outdoor English Corner", zh: "在地國際化的課外英語交流。", en: "On-campus internationalization through English conversation." },
    { date: "2026-03-27", zhTitle: "巴塞隆納 BGS 領導論壇", enTitle: "BGS Leadership Forum, Barcelona", zh: "學生參與國際領導論壇。", en: "Students at an international leadership forum." }
  ],
  marketplace: [
    { zhTitle: "個案與指定讀本", enTitle: "Cases and required readings", zh: "各科指定個案與教科書清單，開學前三週以 Email 公告。", en: "Course cases and textbooks are emailed about three weeks before term starts.", href: "curriculum.html" },
    { zhTitle: "二手書交流", enTitle: "Used-book exchange", zh: "同學可張貼欲出售或徵求的課本與筆記（教學示範，非正式交易平台）。", en: "Students may post books and notes for sale or request (teaching demo, not a commercial marketplace).", href: "contact.html" },
    { zhTitle: "論文格式範本", enTitle: "Thesis templates", zh: "口試與離校所需格式檔，請至下載區取得最新版本。", en: "Defense and leaving-school templates live in Downloads.", href: "downloads.html" }
  ],
  downloads: [
    { zh: "115 學年度碩士招生簡章", en: "2026 local graduate admission brochure", href: "https://www.management.fju.edu.tw/subweb/immba/enroll.php?IID=26" },
    { zh: "上課時間表（現行官網）", en: "Timetable (current official site)", href: "https://www.management.fju.edu.tw/subweb/immba/class.php" },
    { zh: "修業規則／畢業修課規劃", en: "Academic regulations and course map", href: "https://www.management.fju.edu.tw/subweb/immba/class.php" },
    { zh: "論文格式與離校表單", en: "Thesis format and leaving-school forms", href: "https://www.management.fju.edu.tw/subweb/immba/subedit.php?EID=48" },
    { zh: "國際生申請說明", en: "International admissions notes", href: "https://www.management.fju.edu.tw/esubweb/immbaengindex/enroll.php?IID=3" }
  ]
};
